{
 "title": "Home Climate",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "home_sensor_bartemperature_celcius-2",
     "legendFormat": "Temperature Window"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"hometemp\"}",
     "legendFormat": "Temperature Living room"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"bedroomtemp\"}",
     "legendFormat": "Temperature Bedroom"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"kitchentemp\"}",
     "legendFormat": "Temperature Kitchen"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"halltemp\"}",
     "legendFormat": "Temperature Hallway"
    }
   ]
  },
  {
   "title": "Climate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "avg(home_sensor_barpressure_pascal)/100.0",
     "legendFormat": "Pressure"
    },
    {
     "expr": "home_sensor_barhumidity_percent",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "home_sensor_light_dimensionless/1024",
     "legendFormat": "Light"
    }
   ]
  },
  {
   "title": "Temperature Inside",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "home_sensor_temperature_celcius{job=\"hometemp\"}",
     "legendFormat": "Temperature Living room"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"bedroomtemp\"}",
     "legendFormat": "Temperature Bedroom"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"kitchentemp\"}",
     "legendFormat": "Temperature Kitchen"
    },
    {
     "expr": "home_sensor_temperature_celcius{job=\"halltemp\"}",
     "legendFormat": "Temperature Hallway"
    }
   ]
  },
  {
   "title": "Temperature Window",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "home_sensor_bartemperature_celcius-2",
     "legendFormat": "window"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "home_sensor_barhumidity_percent"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 12 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(home_sensor_barpressure_pascal)/100"
    }
   ]
  },
  {
   "title": "Separated barometers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "home_sensor_barpressure_pascal{job=\"hometemp\"}/100",
     "legendFormat": "Pressure Living room"
    },
    {
     "expr": "home_sensor_barpressure_pascal{job=\"bedroomtemp\"}/100",
     "legendFormat": "Pressure Bedroom"
    },
    {
     "expr": "home_sensor_barpressure_pascal{job=\"kitchentemp\"}/100",
     "legendFormat": "Pressure Kitchen"
    },
    {
     "expr": "home_sensor_barpressure_pascal{job=\"halltemp\"}/100",
     "legendFormat": "Pressure Hallway"
    }
   ]
  }
 ]
}